.TH KILO 1
.SH NAME
kilo \- text editor in less than 1000 LOC with syntax highlight and search
.SH SYNOPSIS
.B kilo
.I filename
.SH KEYS
.IP CTRL-S
Save
.IP CTRL-Q
Quit
.IP CTRL-F
Find string in file (ESC to exit search, arrows to navigate)
.SH AUTHOR
Salvatore Sanfilippo aka antirez
.SH LICENSE
BSD 2 clause license
